services:
  api:
    build: .
    container_name: api
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_ENV=${API_ENV}
    restart: always
